Back out "Dedup Redirection Address Type enum definitions in protobuf"
Summary:
Original commit changeset: c8d2e67ee8ac

broke pipelined test
```
27.0.0.1:2222] out: ryu.lib.hub: ERROR: hub: uncaught exception: Traceback (most recent call last):
[magma@10.240.0.17] out: [vagrant@127.0.0.1:2222] out:   File "/home/vagrant/build/python/lib/python3.5/site-packages/ryu/lib/hub.py", line 60, in _launch
[magma@10.240.0.17] out: [vagrant@127.0.0.1:2222] out:     return func(*args, **kwargs)
[magma@10.240.0.17] out: [vagrant@127.0.0.1:2222] out:   File "/home/vagrant/magma/lte/gateway/python/magma/pipelined/tests/app/subscriber.py", line 168, in activate_flows
[magma@10.240.0.17] out: [vagrant@127.0.0.1:2222] out:     dynamic_rules=self._dynamic_rules)
[magma@10.240.0.17] out: [vagrant@127.0.0.1:2222] out:   File "/home/vagrant/magma/lte/gateway/python/magma/pipelined/app/policy_mixin.py", line 200, in activate_rules
[magma@10.240.0.17] out: [vagrant@127.0.0.1:2222] out:     res = self._install_flow_for_rule(imsi, ip_addr, rule)
[magma@10.240.0.17] out: [vagrant@127.0.0.1:2222] out:   File "/home/vagrant/magma/lte/gateway/python/magma/pipelined/app/enforcement.py", line 218, in _install_flow_for_rule
[magma@10.240.0.17] out: [vagrant@127.0.0.1:2222] out:     return self._install_redirect_flow(imsi, ip_addr, rule)
[magma@10.240.0.17] out: [vagrant@127.0.0.1:2222] out:   File "/home/vagrant/magma/lte/gateway/python/magma/pipelined/app/enforcement.py", line 306, in _install_redirect_flow
[magma@10.240.0.17] out: [vagrant@127.0.0.1:2222] out:     self._datapath, self.loop, redirect_request)
[magma@10.240.0.17] out: [vagrant@127.0.0.1:2222] out:   File "/home/vagrant/magma/lte/gateway/python/magma/pipelined/redirect.py", line 78, in handle_redirection
[magma@10.240.0.17] out: [vagrant@127.0.0.1:2222] out:     if rule.redirect.address_type == rule.redirect.SIP_URI:
[magma@10.240.0.17] out: [vagrant@127.0.0.1:2222] out: AttributeError: 'RedirectInformation' object has no attribute 'SIP_URI'
```

Reviewed By: koolzz

Differential Revision: D21089781

fbshipit-source-id: dd947391627aad7dcfbce1936deb69cf2c708e4b