Fix sporadic cwag integ_test failure caused by stale known_hosts keys.
Summary:
Our CWF fab setup eventually breaks if we *manually* ssh into a VM (assuming that VM uses Vagrant-managed custom keypairs).

## Tl;dr
Our fab tests made use of the `known_hosts` file when it shouldn't have, so if we manually polluted that file then eventually fab will throw an error trying to ssh.

## First experienced
- Running `fab integ_test` from `magma/cwf/gateway`
- Error experienced

```
Fatal error: Host key for 127.0.0.1 did not match pre-existing key! Server's key was changed recently, or possible man-in-the-middle attack.

Underlying exception:
    Host key for server '127.0.0.1' does not match: got 'AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIxmhXzpHNZPXdtswS5NNBDYDhTMLTS6BQ4D2uef9YcC8osl7ofwjSOkfonPJz2jWRqH9bKJYzR7fV69rR0FlGA=', expected 'AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFF06VPKVRVIC+EgtcxYXNYD3Omi+GrBD8NjUw74VK2y3pMxM1MRPdRP9okZ0umaUrduavnBpnfO/cP7FtiNy54='
```

## Reproduce
- `cd $MAGMA_ROOT/cwf/gateway`
- `vagrant up cwag_test`
- `ssh vagrant@127.0.0.1 -p 2222 -i $MAGMA_ROOT/cwf/gateway/.vagrant/machines/cwag_test/virtualbox/private_key` -- the cwag_test public key should now be in added to user's known_hosts
- Nuke and restart cwag_test -- this installs a new keypair for cwag_test
- `fab integ_test` now fails -- it consumes the stale public key from known_hosts, breaking ssh into cwag_test

## Resolution
- Ad hoc: `> ~/.ssh/known_hosts` clear user's known hosts file
- [this diff] General fix for CWF integ tests: disable `StrictHostKeyChecking` for local VMs

## Context
- Our Vagrant VMs use [`ssh.insert_key = true`](https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html#config-ssh-insert_key) to insert per-VM ssh keypairs during VM creation phase
- Vagrant automatically disables `StrictHostKeyChecking` since it expects the VM to be destroyed with non-trivial frequency (verify via `vagrant ssh-config`)
- Vagrant also disables updating the user's known_hosts (`UserKnownHostsFile=/dev/null`), preventing generating stale known_hosts entries
- Our CWF `fab integ_test` didn't disable `StrictHostKeyChecking` for local VMs, so it failed when a VM was reloaded but a stale public key was left in `~/.ssh/known_hosts`

Reviewed By: themarwhal

Differential Revision: D20132664

fbshipit-source-id: edb4fa13b383511cc15cb2ed47607e40d9bcf282