Put in missing bracket in user-grafana helm chart
Summary:
Was seeing the following error when trying to deploy to staging:
```
Do you want to perform these actions in workspace "staging"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

helm_release.orc8r: Modifying... [id=orc8r]

Error: rpc error: code = Unknown desc = parse error in "orc8r/charts/metrics/templates/user-grafana.deployment.yaml": template: orc8r/charts/metrics/templates/user-grafana.deployment.yaml:116: unexpected "}" in operand

  on orc8r.tf line 6, in resource "helm_release" "orc8r":
   6: resource "helm_release" "orc8r" {

Releasing state lock. This may take a few moments...
```

And saw what looks to be a missing bracket

Reviewed By: Scott8440

Differential Revision: D20997354

fbshipit-source-id: c1dd816f88bec84ae9912a141d7baf19b9a81743